# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Solutions
    identifier: solutions
    url: /solutions/
    weight: 20
  - name: Network Architecture
    url: /solutions/network-architecture/
    parent: solutions
    weight: 1
  - name: Security Engineering
    url: /solutions/security-engineering/
    parent: solutions
    weight: 2
  - name: Managed Infrastructure
    url: /solutions/managed-infrastructure/
    parent: solutions
    weight: 3
  - name: About
    url: /about/
    weight: 30
  - name: Blog
    url: /insights/
    weight: 40
  - name: Contact
    url: /contact/
    weight: 50
